site_name: DS-Jupyter-Docker
site_description: A template to organize a data science project
site_author: Wes Oler
docs_dir: docs/
repo_name: 'wes-o/ds-jupyter-docker'
repo_url: 'https://github.com/wes-o/ds-jupyter-docker'
nav:
    - Home: 'index.md'
    - Examples:
        - 'All Examples': 'examples.md'
    - About:
        - 'License': 'license.md'
markdown_extensions:
    - toc:
        baselevel: 2
        permalink: "#"
